spring:
  application:
    name: UserInfoService
  rsocket:
    server:
      port: 8093
server:
  port: 8081
rsocket:
  brokers: tcp://10.22.130.17:31999
  jwt-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJDb3Vyc2VJbmZvU2VydmljZSIsImF1ZCI6WyJhIiwiZSIsImkiLCJwIl0sInNhcyI6WyJkIiwiZSIsImYiLCJhIiwidSIsImwiLCJ0Il0sInJvbGVzIjpbImEiLCJlIiwiaSIsInAiXSwiaXNzIjoiUlNvY2tldEJyb2tlciIsImlkIjoiY2ZjMDFmOGYtYzVmMy00YzFjLWIzNTktYWIxZDE4NmU2MGFhIiwib3JncyI6WyIiXSwiaWF0IjoxNjY0ODc4ODk1LCJhdXRob3JpdGllcyI6WyJlIiwiYSIsImkiLCJwIl19.ZjSJYxDtHTusLWEGY0ZgnJXHXYXgKQdg3yaZJMd7AdP0E59p02F7MSe9kjEv-4Mpiem4p8AFPxcvlDTb3ha0g6xThsTeYYTtSFQ513aOnpIdBeN2cV4R5yAzLE_NJUzSHbqMmKt55XA9hH9FwZBhoyeR9AZcP8sUGf7J2WfCv8BNnZWsmJHEyzsfqoqqjgVnHhDvWFryih77MfxXhwogxNnpsHSm5KCZUwJJFkrJbiAAnbb0TRgaaVdCKyW-Q_KDgLBLnSTNh3K7_e2JSfsCXTl55BY6ugk63rN-BjoOdT-gO264zTJ-S24QiU50PrYziCt3AeLMHwdflajVYFPgpA